name: Deploy Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setting up Nodejs envoirment
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.0

      - name: Setup envoirment vars
        run: echo "VITE_API_URL=${{vars.API_URL}}" >> $GITHUB_ENV

      - name: Install requirements
        run: npm ci

      - name: Build static files for vue
        run: npm run build

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download output artifact from te build process
        uses: actions/download-artifact@v4
        with:
          name: dist

      - name: Set up SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
          mkdir -p ~/.ssh
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22 $VPS 'echo connected'

      - name: Deploy via rsync
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22" -r ./dist/* $UPLOAD_PATH --delete

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      VPS: "${{vars.VPS_USER}}@${{vars.VPS_HOST}}"
      UPLOAD_PATH: "${{vars.VPS_USER}}@${{vars.VPS_HOST}}:${{vars.VPS_DIR}}"

    # Optional: Define an environment for deployment, like production
    environment:
      name: production
      url: https://matthijsverheijen.com
